### ISSUE TITLE
non user's entities returned on listing entpoints

### ISSUE THREAD

**Issue by Quentigus** [jeremyben/json-server-auth#26]
Hello,

When I call a listing route (ex : `GET /characters`), all entities are returned, not just user's entities.

Versions : 
- json-server : 0.16.1
- json-server-auth : 2.0.0

route.json fie:
`{
    "/users*": "/640/users$1",
    "/characters*": "/600/characters$1"
}`

db.json file : 
`{
    "users": [
        { "id": 1, "email": "first@mail.com",      "password: "..." },
        { "id": 2, "email": "second@mail.com", "password: "..." }
    ],
    "characters": [
        { "id": 1, "name": "char1", "userId: 1 },
        { "id": 2, "name": "char2", "userId: 2 }
    ]
}`

Is not working with codes : 600, 640

Thanks

**Comment by jeremyben** [comment]
Yeah, this is not implemented yet: https://github.com/jeremyben/json-server-auth/blob/master/src/guards.ts#L105-L110

Might need some help. But first, I need to recreate the whole request with all query params: https://github.com/jeremyben/json-server-auth/blob/master/src/guards.ts#L68

So yeah, it is a lot of work.
Since this is for prototyping purposes to emulate authorization flow, not production code, I intentionally make some requests loose instead of having false negatives.

Apart from that, json-server auth is about authorization, not filtering, so you should make your query filter by userId.

**Comment by Quentigus** [comment]
Thanks for your answer, I had misunderstood this comment.
I will filter inside my service :+1: 

Perhaps a viable alternative would be to return only entities with an "userId" equals to the "sub" value ?

EDIT : You can close this issue if you want
