### ISSUE TITLE
How to configure JWT expiration time?

### ISSUE THREAD

**Issue by ghost** [jeremyben/json-server-auth#8]
Hi,

Is it possible to set JWT token expiration time?
Currently it expire after 1 hour, it is too short for comfortable work with api.
Please, add configuration to change this.

Thanks

**Comment by jeremyben** [comment]
That kind of config is planned, but has to be carefully done since this is an add-on to json-server, and config should be possible from json-server as well.

I chose an expiration time of 1h, since it's a common practice with JWT for security reasons (you don't want a stateless token to have valid credentials too long in case of a theft). A "close to production" solution would be to implement a refresh token, which is also planned.

In the meantime, and I know it's not ideal, you can change the value in `node_modules/json-server-auth/dist/constants.js`.

**Comment by ghost** [comment]
I use json-server docker image so cant change value in constants.js.
I will wait for config to do that.
Thanks
